name: Deploy Bolamiga to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to EC2
      run: |
        # Create deployment package
        zip -r bolamiga-deployment.zip . -x "*.git*" "venv/*" "__pycache__/*"
        
        # Upload to S3 for backup
        aws s3 cp bolamiga-deployment.zip s3://bolamiga-deployments/$(date +%Y%m%d-%H%M%S)/
        
        # Deploy to existing instance or create new one
        chmod +x deploy.sh
        ./deploy.sh
        
    - name: Verify deployment
      run: |
        # Wait for deployment to complete
        sleep 30
        
        # Test the application
        INSTANCE_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=bolamiga-game-server" "Name=instance-state-name,Values=running" \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
          
        echo "Testing deployment at http://$INSTANCE_IP:5000"
        curl -f "http://$INSTANCE_IP:5000" || exit 1
        
        echo "✅ Deployment successful!"
        echo "🎮 Game URL: http://$INSTANCE_IP:5000"